@echo off
setlocal

set ROOT=%~dp0
set OUT=%ROOT%..\DataField42.Core\Models\Bf1942ClientPatches.cs
set /a _seq=0

call :assemble "call hook missing map.asm"      9494F
if errorlevel 1 goto fail
call :assemble "hook function missing map.asm"  0BF10
if errorlevel 1 goto fail
call :assemble "call hook missing mod.asm"      94EF5
if errorlevel 1 goto fail
call :assemble "hook function missing mod.asm"  0C0F0
if errorlevel 1 goto fail

echo Generating Bf1942ClientPatches.cs...
powershell -NoProfile -Command ^
    "$out = '%OUT%';" ^
    "$patches = Get-ChildItem '%TEMP%\patch_*.raw' | Sort-Object Name | ForEach-Object {" ^
    "    $off = ($_.BaseName -split '_', 3)[2];" ^
    "    $hex = ([IO.File]::ReadAllBytes($_.FullName) | ForEach-Object { '0x{0:X2}' -f $_ }) -join ', ';" ^
    "    '        (0x' + $off + ', new byte[] { ' + $hex + ' }),';" ^
    "};" ^
    "$header = @(" ^
    "    '/// <summary>'," ^
    "    '/// The patches required to hook DataField42 into BF1942.'," ^
    "    '/// </summary>'," ^
    "    '/// <remarks>'," ^
    "    '/// This file was generated by assemble_patches.bat. Do not edit manually.'," ^
    "    '/// </remarks>'," ^
    "    'internal static class Bf1942ClientPatches'," ^
    "    '{'," ^
    "    '    internal static readonly (int Offset, byte[] Bytes)[] Patches ='," ^
    "    '    {'" ^
    ");" ^
    "$footer = @('    };', '}');" ^
    "$lines = $header + $patches + $footer;" ^
    "[IO.File]::WriteAllLines($out, $lines, [Text.Encoding]::UTF8);"
if errorlevel 1 goto fail

del "%TEMP%\patch_*_*.raw"

echo Done. Written to %OUT%
exit /b 0

:assemble
set /a _seq+=1
if %_seq% lss 10 (set _seqpad=0%_seq%) else (set _seqpad=%_seq%)
echo Assembling "%~1"...
nasm -f bin "%ROOT%%~1" -o "%TEMP%\patch_%_seqpad%_%~2.raw"
if errorlevel 1 (
    echo Assembly of "%~1" failed.
    exit /b 1
)
exit /b 0

:fail
echo Failed.
exit /b 1
