@echo off
setlocal

set ROOT=%~dp0

set TMP_0=%TEMP%\patch_0BF10.raw
set TMP_1=%TEMP%\patch_0C0F0.raw
set OUT=%ROOT%..\DataField42.Core\Models\Bf1942ClientPatches.cs

echo Assembling "hook function missing map.asm"...
nasm -f bin "%ROOT%hook function missing map.asm" -o "%TMP_0%"
if errorlevel 1 goto fail

echo Assembling "hook function missing mod.asm"...
nasm -f bin "%ROOT%hook function missing mod.asm" -o "%TMP_1%"
if errorlevel 1 goto fail

echo Generating Bf1942ClientPatches.cs...
powershell -NoProfile -Command ^
    "$b0 = [IO.File]::ReadAllBytes('%TMP_0%');" ^
    "$b1 = [IO.File]::ReadAllBytes('%TMP_1%');" ^
    "function Fmt($b, $off) {" ^
    "    $hex = ($b | ForEach-Object { '0x{0:X2}' -f $_ }) -join ', ';" ^
    "    return '        (0x' + $off + ', new byte[] { ' + $hex + ' }),';" ^
    "};" ^
    "$lines = @(" ^
    "    '// <auto-generated>'," ^
    "    '// This file was generated by assemble_patches.bat. Do not edit manually.'," ^
    "    '// </auto-generated>'," ^
    "    'internal static class Bf1942ClientPatches'," ^
    "    '{'," ^
    "    '    internal static readonly (int Offset, byte[] Bytes)[] Patches ='," ^
    "    '    {'," ^
    "    (Fmt $b0 '0BF10')," ^
    "    (Fmt $b1 '0C0F0')," ^
    "    '    };'," ^
    "    '}'" ^
    "); [IO.File]::WriteAllLines('%OUT%', $lines, [Text.Encoding]::UTF8);"
if errorlevel 1 goto fail

del "%TMP_0%"
del "%TMP_1%"

echo Done. Written to %OUT%
exit /b 0

:fail
echo Failed.
exit /b 1
